work_dir: ./
save_dir: ./saved_model

# feeder
num_worker: 8
use_mnist: True

# model
model: model.Model
model_args:
  block_args: [[1,16,32],[32,32]]

#optim
weight_decay: 0.0004
lr: 0.1
step: [15]
warm_up_epoch: 5

# training
device: [0]
batch_size: 64
test_batch_size: 64
num_epoch: 20
nesterov: True